apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-cluster
  labels:
    app: ceph-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-cluster
  template:
    metadata:
      labels:
        app: ceph-cluster
    spec:
      hostname: ceph-service
      securityContext: {}
      containers:
        - name: ceph-cluster
          securityContext:
            runAsUser: 0
          runAsNonRoot: false
          image: ghcr.io/snapp-incubator/ceph-testing-container:v14.2.6
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
            port: http
          initialDelaySeconds: 50
          periodSeconds: 10
          timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
            port: http
          periodSeconds: 10
          initialDelaySeconds: 50
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-service
  labels:
    app: ceph-cluster
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: ceph-cluster
